import { Order } from "./types";

export const mockOrders: Order[] = [
  {
    id: "ord-demo-005",
    orderNumber: "ORD-2026-0052",
    stage: "rfq_received",
    source: "email",
    createdAt: "2026-03-13T10:05:00Z",
    emailSubject: "RFQ — CNC machining parts for Q2 production run",
    customer: {
      id: "cust-demo-005",
      name: "Tom Wagner",
      email: "tom.wagner@pacificindustrial.com",
      phone: "(555) 401-8833",
      company: "Pacific Industrial Co.",
      billingAddress: "4200 Harbor Blvd, Suite 100, Long Beach, CA 90802",
      shippingAddress: "4200 Harbor Blvd, Dock 3, Long Beach, CA 90802",
    },
    attachments: [
      {
        id: "att-demo-005",
        fileName: "RFQ-Pacific-Q2-2026.csv",
        mimeType: "text/csv",
        size: 28_400,
        url: "/rfq-request-march.csv",
      },
    ],
    lineItems: [
      {
        id: "li-demo-051",
        lineNumber: 1,
        rawText: "200 Aluminum Bracket AL-BRK-100",
        parsedSku: "AL-BRK-100",
        parsedProductName: "Aluminum Bracket 100mm",
        parsedQuantity: 200,
        parsedUom: "units",
        parsedUnitPrice: 8.75,
        requestedDueDate: "2026-04-15",
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "AL-BRK-100",
            catalogName: "Aluminum Bracket 100mm",
            catalogDescription: "CNC machined aluminum bracket, 100mm span.",
            catalogPrice: 8.75,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-052",
        lineNumber: 2,
        rawText: "50 stainless dowel pins",
        parsedSku: null,
        parsedProductName: "Stainless Dowel Pin",
        parsedQuantity: 50,
        parsedUom: "units",
        parsedUnitPrice: null,
        matchStatus: "partial",
        confidence: 62,
        matchedCatalogItems: [
          {
            catalogSku: "DP-SS-6",
            catalogName: "Stainless Dowel Pin 6mm",
            catalogDescription: "303 stainless dowel pin, 6mm diameter.",
            catalogPrice: 1.2,
            catalogUom: "unit",
          },
          {
            catalogSku: "DP-SS-8",
            catalogName: "Stainless Dowel Pin 8mm",
            catalogDescription: "303 stainless dowel pin, 8mm diameter.",
            catalogPrice: 1.45,
            catalogUom: "unit",
          },
        ],
        issues: [
          "No SKU provided — diameter not specified",
          "Multiple sizes available (6mm, 8mm)",
        ],
      },
      {
        id: "li-demo-053",
        lineNumber: 3,
        rawText: "30 Titanium Shaft Collar TC-25 or TC-30",
        parsedSku: "TC-25",
        parsedProductName: "Titanium Shaft Collar",
        parsedQuantity: 30,
        parsedUom: "units",
        parsedUnitPrice: 22.0,
        matchStatus: "conflict",
        confidence: 48,
        matchedCatalogItems: [
          {
            catalogSku: "TC-25",
            catalogName: "Titanium Shaft Collar 25mm",
            catalogDescription: "Grade 5 titanium collar, 25mm ID.",
            catalogPrice: 18.5,
            catalogUom: "unit",
          },
          {
            catalogSku: "TC-30",
            catalogName: "Titanium Shaft Collar 30mm",
            catalogDescription: "Grade 5 titanium collar, 30mm ID.",
            catalogPrice: 24.0,
            catalogUom: "unit",
          },
        ],
        issues: [
          "Source mentions both TC-25 and TC-30 — bore size unclear",
          "Price differs between options ($18.50 vs $24.00)",
          "Manual review required to resolve conflict",
        ],
      },
      {
        id: "li-demo-054",
        lineNumber: 4,
        rawText: "100 custom spacers ???",
        parsedSku: null,
        parsedProductName: "Custom Spacer",
        parsedQuantity: 100,
        parsedUom: "units",
        parsedUnitPrice: null,
        matchStatus: "unmatched",
        confidence: 0,
        matchedCatalogItems: [],
        issues: [
          "No matching item found in product catalog",
          "Material and dimensions not specified",
          "\"Custom\" suggests a non-standard part — verify with customer",
        ],
      },
      {
        id: "li-demo-055",
        lineNumber: 5,
        rawText: "80 Precision Bushing PB-440 rev B",
        parsedSku: "PB-440",
        parsedProductName: "Precision Bushing",
        parsedQuantity: 80,
        parsedUom: "units",
        parsedUnitPrice: 6.5,
        requestedDueDate: "2026-04-20",
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "PB-440",
            catalogName: "Precision Bushing 440C",
            catalogDescription: "440C stainless precision bushing, standard bore.",
            catalogPrice: 6.5,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 5,
    parseConfidence: 88,
    parseMissingFields: ["price", "dueDate"],
    ingestionSourceLabel: "Outlook - RFQ CSV",
    demoFlow: {
      scenario: "rfq_csv",
      stage: "rfq_received",
    },
  },
  {
    id: "ord-demo-004",
    orderNumber: "ORD-2026-0051",
    stage: "po_mismatch",
    source: "email",
    createdAt: "2026-03-13T09:35:00Z",
    emailSubject: "PO-2026-0342 — Updated quantities (please expedite)",
    customer: {
      id: "cust-demo-001",
      name: "James Whitfield",
      email: "james.whitfield@acmedist.com",
      phone: "(555) 234-8901",
      company: "Acme Distributors Inc.",
      billingAddress: "1200 Commerce Blvd, Suite 400, Austin, TX 73301",
      shippingAddress: "850 Warehouse Dr, Unit 12, Austin, TX 73344",
    },
    attachments: [
      {
        id: "att-demo-004",
        fileName: "PO-2026-0342-mismatch.pdf",
        mimeType: "application/pdf",
        size: 178_000,
        url: "/po-mismatch-q-2026-0047.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-demo-041",
        lineNumber: 1,
        rawText: "120 Valve Body - Stainless 316 VB-316-90 @ 44.90 due 2026-03-28 rev D",
        parsedSku: "VB-316-90",
        parsedProductName: "Valve Body - Stainless 316",
        parsedQuantity: 120,
        parsedUom: "units",
        parsedUnitPrice: 44.9,
        requestedDueDate: "2026-03-28",
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "VB-316-90",
            catalogName: "Valve Body - Stainless 316",
            catalogDescription: "Stainless valve body for industrial assemblies.",
            catalogPrice: 44.9,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-042",
        lineNumber: 2,
        rawText: "90 Pump Impeller 4in IMP-4-220 @ 78.00 due 2026-03-29 rev B",
        parsedSku: "IMP-4-220",
        parsedProductName: "Pump Impeller 4in",
        parsedQuantity: 90,
        parsedUom: "units",
        parsedUnitPrice: 78.0,
        requestedDueDate: "2026-03-29",
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "IMP-4-220",
            catalogName: "Pump Impeller 4in",
            catalogDescription: "CNC machined 4-inch pump impeller.",
            catalogPrice: 78.0,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-043",
        lineNumber: 3,
        rawText: "180 Seal Kit High Temp SK-HT-55 @ 12.40 due 2026-03-22 rev A",
        parsedSku: "SK-HT-55",
        parsedProductName: "Seal Kit High Temp",
        parsedQuantity: 180,
        parsedUom: "kits",
        parsedUnitPrice: 12.4,
        requestedDueDate: "2026-03-22",
        matchStatus: "confirmed",
        confidence: 96,
        matchedCatalogItems: [
          {
            catalogSku: "SK-HT-55",
            catalogName: "Seal Kit High Temp",
            catalogDescription: "High temperature seal kit.",
            catalogPrice: 12.4,
            catalogUom: "kit",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 3,
    poNumber: "PO-2026-0342",
    dueDate: "2026-03-22",
    parseConfidence: 98,
    ingestionSourceLabel: "Outlook - PO PDF",
    demoFlow: {
      scenario: "po_mismatch",
      stage: "po_validated",
      quoteNumber: "Q-2026-0047",
      poNumber: "PO-2026-0342",
      quoteComparison: {
        overallMatch: false,
        checks: [
          {
            field: "price",
            matches: false,
            quoteValue: "VB-316-90 = $42.50",
            incomingValue: "VB-316-90 = $44.90",
            note: "Price increased vs quoted amount",
          },
          {
            field: "quantity",
            matches: false,
            quoteValue: "IMP-4-220 = 60",
            incomingValue: "IMP-4-220 = 90",
            note: "Quantity increased vs quote",
          },
          {
            field: "dueDate",
            matches: false,
            quoteValue: "SK-HT-55 = 2026-03-30",
            incomingValue: "SK-HT-55 = 2026-03-22",
            note: "Due date pulled in by 8 days",
          },
          {
            field: "drawingRev",
            matches: false,
            quoteValue: "VB-316-90 Rev C",
            incomingValue: "VB-316-90 Rev D",
            note: "Drawing rev changed",
          },
        ],
      },
      correctionDraftEmail: {
        to: "james.whitfield@acmedist.com",
        subject: "PO-2026-0342 needs correction to match Quote Q-2026-0047",
        body: "Hi James,\n\nThanks for sending PO-2026-0342. We detected differences against Quote Q-2026-0047:\n- Price: VB-316-90 is $44.90 on PO vs $42.50 quoted\n- Quantity: IMP-4-220 is 90 on PO vs 60 quoted\n- Due date: SK-HT-55 is 2026-03-22 on PO vs 2026-03-30 quoted\n- Drawing rev: VB-316-90 is Rev D on PO vs Rev C quoted\n\nPlease send a corrected PO or confirm that you want us to requote these lines.\n\nBest,\nHexa Sales Ops",
      },
      quoteSummary: {
        quoteNumber: "Q-2026-0047",
        items: [
          { sku: "VB-316-90", name: "Valve Body - Stainless 316", qty: 120, unitPrice: 42.5 },
          { sku: "IMP-4-220", name: "Pump Impeller 4in", qty: 60, unitPrice: 78.0 },
          { sku: "SK-HT-55", name: "Seal Kit High Temp", qty: 180, unitPrice: 12.4 },
        ],
        subtotal: 11922.0,
        sentAt: "2026-03-12T14:30:00Z",
        sentTo: "james.whitfield@acmedist.com",
      },
      erpSync: {
        state: "blocked",
        timeline: [
          {
            label: "PO parsed from email attachment",
            state: "queued",
            at: "2026-03-13T09:35:42Z",
          },
          {
            label: "Quote comparison check failed",
            state: "blocked",
            at: "2026-03-13T09:36:14Z",
          },
        ],
      },
    },
  },
  {
    id: "ord-demo-003",
    orderNumber: "ORD-2026-0050",
    stage: "pushed_to_mrp",
    source: "email",
    createdAt: "2026-03-13T09:20:00Z",
    emailSubject: "PO-2026-0341 — Confirmed against Quote Q-2026-0047",
    customer: {
      id: "cust-demo-001",
      name: "James Whitfield",
      email: "james.whitfield@acmedist.com",
      phone: "(555) 234-8901",
      company: "Acme Distributors Inc.",
      billingAddress: "1200 Commerce Blvd, Suite 400, Austin, TX 73301",
      shippingAddress: "850 Warehouse Dr, Unit 12, Austin, TX 73344",
    },
    attachments: [
      {
        id: "att-demo-003",
        fileName: "PO-2026-0341-match.pdf",
        mimeType: "application/pdf",
        size: 165_000,
        url: "/po-match-q-2026-0047.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-demo-031",
        lineNumber: 1,
        rawText: "120 Valve Body - Stainless 316 VB-316-90 @ 42.50 due 2026-03-28 rev C",
        parsedSku: "VB-316-90",
        parsedProductName: "Valve Body - Stainless 316",
        parsedQuantity: 120,
        parsedUom: "units",
        parsedUnitPrice: 42.5,
        requestedDueDate: "2026-03-28",
        matchStatus: "confirmed",
        confidence: 99,
        matchedCatalogItems: [
          {
            catalogSku: "VB-316-90",
            catalogName: "Valve Body - Stainless 316",
            catalogDescription: "Stainless valve body for industrial assemblies.",
            catalogPrice: 42.5,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-032",
        lineNumber: 2,
        rawText: "60 Pump Impeller 4in IMP-4-220 @ 78.00 due 2026-03-29 rev B",
        parsedSku: "IMP-4-220",
        parsedProductName: "Pump Impeller 4in",
        parsedQuantity: 60,
        parsedUom: "units",
        parsedUnitPrice: 78.0,
        requestedDueDate: "2026-03-29",
        matchStatus: "confirmed",
        confidence: 99,
        matchedCatalogItems: [
          {
            catalogSku: "IMP-4-220",
            catalogName: "Pump Impeller 4in",
            catalogDescription: "CNC machined 4-inch pump impeller.",
            catalogPrice: 78.0,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-033",
        lineNumber: 3,
        rawText: "180 Seal Kit High Temp SK-HT-55 @ 12.40 due 2026-03-30 rev A",
        parsedSku: "SK-HT-55",
        parsedProductName: "Seal Kit High Temp",
        parsedQuantity: 180,
        parsedUom: "kits",
        parsedUnitPrice: 12.4,
        requestedDueDate: "2026-03-30",
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "SK-HT-55",
            catalogName: "Seal Kit High Temp",
            catalogDescription: "High temperature seal kit.",
            catalogPrice: 12.4,
            catalogUom: "kit",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 3,
    poNumber: "PO-2026-0341",
    dueDate: "2026-03-30",
    parseConfidence: 99,
    ingestionSourceLabel: "Outlook - PO PDF",
    mrpRoutedAt: "2026-03-13T09:23:07Z",
    demoFlow: {
      scenario: "po_match",
      stage: "po_validated",
      quoteNumber: "Q-2026-0047",
      poNumber: "PO-2026-0341",
      quoteComparison: {
        overallMatch: true,
        checks: [
          {
            field: "price",
            matches: true,
            quoteValue: "All lines matched quoted prices",
            incomingValue: "All lines matched quoted prices",
          },
          {
            field: "quantity",
            matches: true,
            quoteValue: "All line quantities unchanged",
            incomingValue: "All line quantities unchanged",
          },
          {
            field: "dueDate",
            matches: true,
            quoteValue: "Due dates aligned with quote",
            incomingValue: "Due dates aligned with quote",
          },
          {
            field: "drawingRev",
            matches: true,
            quoteValue: "All lines at approved revisions",
            incomingValue: "All lines at approved revisions",
          },
        ],
      },
      erpSync: {
        state: "acknowledged",
        timeline: [
          {
            label: "PO parsed from email attachment",
            state: "queued",
            at: "2026-03-13T09:20:12Z",
          },
          {
            label: "PO matched against quote Q-2026-0047",
            state: "sent",
            at: "2026-03-13T09:21:04Z",
          },
          {
            label: "ERP order acknowledged",
            state: "acknowledged",
            at: "2026-03-13T09:23:07Z",
          },
        ],
      },
      quoteSummary: {
        quoteNumber: "Q-2026-0047",
        items: [
          { sku: "VB-316-90", name: "Valve Body - Stainless 316", qty: 120, unitPrice: 42.5 },
          { sku: "IMP-4-220", name: "Pump Impeller 4in", qty: 60, unitPrice: 78.0 },
          { sku: "SK-HT-55", name: "Seal Kit High Temp", qty: 180, unitPrice: 12.4 },
        ],
        subtotal: 11922.0,
        sentAt: "2026-03-12T14:30:00Z",
        sentTo: "james.whitfield@acmedist.com",
      },
      poConfirmation: {
        poNumber: "PO-2026-0341",
        receivedAt: "2026-03-13T09:20:00Z",
        matchesQuote: true,
      },
      mrpPush: {
        pushedAt: "2026-03-13T09:23:07Z",
        erpOrderId: "ERP-2026-0341",
      },
    },
  },
  {
    id: "ord-demo-002",
    orderNumber: "ORD-2026-0049",
    stage: "quote_sent",
    source: "email",
    createdAt: "2026-03-13T08:55:00Z",
    emailSubject: "Quick RFQ — handwritten shop-floor request",
    customer: {
      id: "cust-demo-002",
      name: "Ravi Patel",
      email: "ravi.patel@summitfab.com",
      phone: "(555) 778-4010",
      company: "Summit Fabrication",
      billingAddress: "22 Foundry Lane, Pittsburgh, PA 15201",
      shippingAddress: "22 Foundry Lane, Dock 2, Pittsburgh, PA 15201",
    },
    attachments: [
      {
        id: "att-demo-002",
        fileName: "RFQ-handwritten-note.pdf",
        mimeType: "application/pdf",
        size: 145_000,
        url: "/rfq-handwritten-note.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-demo-021",
        lineNumber: 1,
        rawText: "30 shaft collars SC-12 rev B",
        parsedSku: "SC-12",
        parsedProductName: "Shaft Collar 12mm",
        parsedQuantity: 30,
        parsedUom: "units",
        parsedUnitPrice: 6.9,
        requestedDueDate: "2026-03-25",
        matchStatus: "confirmed",
        confidence: 93,
        matchedCatalogItems: [
          {
            catalogSku: "SC-12",
            catalogName: "Shaft Collar 12mm",
            catalogDescription: "Steel shaft collar, 12mm ID.",
            catalogPrice: 6.9,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-022",
        lineNumber: 2,
        rawText: "75 bearings BB-6205 rev C",
        parsedSku: "BB-6205",
        parsedProductName: "Deep Groove Bearing 6205",
        parsedQuantity: 75,
        parsedUom: "units",
        parsedUnitPrice: 4.8,
        requestedDueDate: "2026-03-25",
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "BB-6205",
            catalogName: "Deep Groove Bearing 6205-2RS",
            catalogDescription: "Sealed bearing, both sides.",
            catalogPrice: 4.8,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-023",
        lineNumber: 3,
        rawText: "20 gasket packs GK-STD-25",
        parsedSku: "GK-STD-25",
        parsedProductName: "Standard Gasket Pack",
        parsedQuantity: 20,
        parsedUom: "packs",
        parsedUnitPrice: 11.5,
        requestedDueDate: "2026-03-25",
        matchStatus: "confirmed",
        confidence: 94,
        matchedCatalogItems: [
          {
            catalogSku: "GK-STD-25",
            catalogName: "Standard Gasket Pack",
            catalogDescription: "General purpose gasket set.",
            catalogPrice: 11.5,
            catalogUom: "pack",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 3,
    parseConfidence: 94,
    ingestionSourceLabel: "Outlook - Handwritten RFQ",
    demoFlow: {
      scenario: "rfq_handwritten",
      stage: "quote_prepared",
      quoteNumber: "Q-2026-0048",
      quoteSummary: {
        quoteNumber: "Q-2026-0048",
        items: [
          { sku: "SC-12", name: "Shaft Collar 12mm", qty: 30, unitPrice: 6.9 },
          { sku: "BB-6205", name: "Deep Groove Bearing 6205-2RS", qty: 75, unitPrice: 4.8 },
          { sku: "GK-STD-25", name: "Standard Gasket Pack", qty: 20, unitPrice: 11.5 },
        ],
        subtotal: 797.0,
        sentAt: "2026-03-13T08:40:00Z",
        sentTo: "ravi.patel@summitfab.com",
      },
    },
  },
  {
    id: "ord-demo-001",
    orderNumber: "ORD-2026-0048",
    stage: "quote_sent",
    source: "email",
    createdAt: "2026-03-13T08:40:00Z",
    emailSubject: "RFQ-2026-1187 — Need quote for March machining lot (CSV)",
    customer: {
      id: "cust-demo-003",
      name: "Elena Marsh",
      email: "elena.marsh@northfieldcomponents.com",
      phone: "(555) 220-1178",
      company: "Northfield Components",
      billingAddress: "810 Industrial Parkway, Dayton, OH 45402",
      shippingAddress: "810 Industrial Parkway, Gate 6, Dayton, OH 45402",
    },
    attachments: [
      {
        id: "att-demo-001",
        fileName: "RFQ-2026-1187-Northfield.csv",
        mimeType: "text/csv",
        size: 34_500,
        url: "/rfq-request-march.csv",
      },
    ],
    lineItems: [
      {
        id: "li-demo-011",
        lineNumber: 1,
        rawText: "120 Valve Body - Stainless 316 VB-316-90 rev C",
        parsedSku: "VB-316-90",
        parsedProductName: "Valve Body - Stainless 316",
        parsedQuantity: 120,
        parsedUom: "units",
        parsedUnitPrice: 42.5,
        requestedDueDate: "2026-03-28",
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "VB-316-90",
            catalogName: "Valve Body - Stainless 316",
            catalogDescription: "Stainless valve body for industrial assemblies.",
            catalogPrice: 42.5,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-012",
        lineNumber: 2,
        rawText: "60 Pump Impeller 4in IMP-4-220 rev B",
        parsedSku: "IMP-4-220",
        parsedProductName: "Pump Impeller 4in",
        parsedQuantity: 60,
        parsedUom: "units",
        parsedUnitPrice: 78.0,
        requestedDueDate: "2026-03-29",
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "IMP-4-220",
            catalogName: "Pump Impeller 4in",
            catalogDescription: "CNC machined 4-inch pump impeller.",
            catalogPrice: 78.0,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-demo-013",
        lineNumber: 3,
        rawText: "180 Seal Kit High Temp SK-HT-55 rev A",
        parsedSku: "SK-HT-55",
        parsedProductName: "Seal Kit High Temp",
        parsedQuantity: 180,
        parsedUom: "kits",
        parsedUnitPrice: 12.4,
        requestedDueDate: "2026-03-30",
        matchStatus: "confirmed",
        confidence: 96,
        matchedCatalogItems: [
          {
            catalogSku: "SK-HT-55",
            catalogName: "Seal Kit High Temp",
            catalogDescription: "High temperature seal kit.",
            catalogPrice: 12.4,
            catalogUom: "kit",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 3,
    parseConfidence: 97,
    ingestionSourceLabel: "Outlook - RFQ CSV",
    demoFlow: {
      scenario: "rfq_csv",
      stage: "quote_prepared",
      quoteNumber: "Q-2026-0047",
      clarifications: [
        {
          questions: [
            "CSV lists 'Seal Kit High Temp' without specifying the operating temperature range — is this the SK-HT-55 (up to 400°F) or SK-HT-80 (up to 800°F)?",
            "Requested due date for Pump Impeller 4in is 2026-03-29 — can you confirm this is firm or if there is flexibility?",
          ],
          emailSent: {
            to: "elena.marsh@northfieldcomponents.com",
            subject: "RFQ-2026-1187 — Clarification needed for 2 items",
            body: "Hi Elena,\n\nThank you for sending over the March machining lot RFQ. We have a couple of questions before we can finalize pricing:\n\n1. The Seal Kit High Temp — is this the SK-HT-55 (rated to 400°F) or the SK-HT-80 (rated to 800°F)?\n2. The due date for the Pump Impeller 4in is listed as Mar 29 — is that firm?\n\nBest regards,\nHexa Sales Team",
            sentAt: "2026-03-13T09:00:00Z",
          },
          replyReceived: {
            body: "Hi, the seal kit is the SK-HT-55 (400°F version). And yes, March 29 is firm for the impeller — we need it for a scheduled maintenance window.",
            receivedAt: "2026-03-13T09:25:00Z",
            parsedAnswers: [
              "Seal Kit is SK-HT-55 (400°F rating) — confirmed",
              "Pump Impeller due date Mar 29 is firm — scheduled maintenance window",
            ],
          },
        },
      ],
      quoteSummary: {
        quoteNumber: "Q-2026-0047",
        items: [
          { sku: "VB-316-90", name: "Valve Body - Stainless 316", qty: 120, unitPrice: 42.5 },
          { sku: "IMP-4-220", name: "Pump Impeller 4in", qty: 60, unitPrice: 78.0 },
          { sku: "SK-HT-55", name: "Seal Kit High Temp", qty: 180, unitPrice: 12.4 },
        ],
        subtotal: 11922.0,
        sentAt: "2026-03-13T10:15:00Z",
        sentTo: "elena.marsh@northfieldcomponents.com",
      },
    },
  },
  {
    id: "ord-001",
    orderNumber: "ORD-2026-0047",
    stage: "pushed_to_mrp",
    source: "email",
    createdAt: "2026-03-04T09:15:00Z",
    emailSubject: "Q1 Restock Order - Urgent",
    customer: {
      id: "cust-001",
      name: "James Whitfield",
      email: "james.whitfield@acmedist.com",
      phone: "(555) 234-8901",
      company: "Acme Distributors Inc.",
      billingAddress: "1200 Commerce Blvd, Suite 400, Austin, TX 73301",
      shippingAddress: "850 Warehouse Dr, Unit 12, Austin, TX 73344",
    },
    attachments: [
      {
        id: "att-001",
        fileName: "order-items-handwritten.png",
        mimeType: "image/png",
        size: 2_150_000,
        url: "/sample-handwritten-order.png",
      },
    ],
    lineItems: [
      {
        id: "li-001",
        lineNumber: 1,
        rawText: "50x Blue Widget 10pk  WDG-BLU-10",
        parsedSku: "WDG-BLU-10",
        parsedProductName: "Blue Widget 10-Pack",
        parsedQuantity: 50,
        parsedUom: "cases",
        parsedUnitPrice: 24.99,
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "WDG-BLU-10",
            catalogName: "Blue Widget 10-Pack",
            catalogDescription:
              "Premium blue widgets, 10 units per case. Industrial grade.",
            catalogPrice: 24.99,
            catalogUom: "case",
          },
        ],
        issues: [],
      },
      {
        id: "li-005",
        lineNumber: 2,
        rawText: "100 Copper Fasteners CF-250",
        parsedSku: "CF-250",
        parsedProductName: "Copper Fastener 250-Count Bag",
        parsedQuantity: 100,
        parsedUom: "bags",
        parsedUnitPrice: 8.75,
        matchStatus: "confirmed",
        confidence: 96,
        matchedCatalogItems: [
          {
            catalogSku: "CF-250",
            catalogName: "Copper Fastener 250-Count Bag",
            catalogDescription:
              "High-quality copper fasteners, 250 per bag. Corrosion resistant.",
            catalogPrice: 8.75,
            catalogUom: "bag",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 2,
    poNumber: "PO-2026-0341",
    dueDate: "21 Mar 2026",
    shipTo: "850 Warehouse Dr, Unit 12, Austin, TX 73344",
    shipVia: "Standard Freight",
    paymentTerms: "Net 30",
    parseConfidence: 97,
    parseMissingFields: [],
    mrpRoutedAt: "2026-03-04T09:16:00Z",
    ingestionSourceLabel: "taskpane:email",
    demoFlow: {
      scenario: "po_match",
      stage: "po_validated",
      quoteNumber: "Q-2026-0041",
      poNumber: "PO-2026-0341",
      quoteComparison: {
        overallMatch: true,
        checks: [
          { field: "price", matches: true, quoteValue: "All lines matched", incomingValue: "All lines matched" },
          { field: "quantity", matches: true, quoteValue: "All quantities matched", incomingValue: "All quantities matched" },
          { field: "dueDate", matches: true, quoteValue: "Due dates aligned", incomingValue: "Due dates aligned" },
          { field: "drawingRev", matches: true, quoteValue: "Revisions matched", incomingValue: "Revisions matched" },
        ],
      },
      quoteSummary: {
        quoteNumber: "Q-2026-0041",
        items: [
          { sku: "WDG-BLU-10", name: "Blue Widget 10-Pack", qty: 50, unitPrice: 24.99 },
          { sku: "CF-250", name: "Copper Fastener 250-Count Bag", qty: 100, unitPrice: 8.75 },
        ],
        subtotal: 2124.5,
        sentAt: "2026-03-03T14:00:00Z",
        sentTo: "james.whitfield@acmedist.com",
      },
      poConfirmation: {
        poNumber: "PO-2026-0341",
        receivedAt: "2026-03-04T09:15:00Z",
        matchesQuote: true,
      },
      mrpPush: {
        pushedAt: "2026-03-04T09:16:00Z",
        erpOrderId: "ERP-2026-0341",
      },
      erpSync: {
        state: "acknowledged",
        timeline: [
          { label: "PO parsed from email attachment", state: "queued", at: "2026-03-04T09:15:12Z" },
          { label: "PO matched against quote Q-2026-0041", state: "sent", at: "2026-03-04T09:15:45Z" },
          { label: "ERP order acknowledged", state: "acknowledged", at: "2026-03-04T09:16:00Z" },
        ],
      },
    },
  },
  {
    id: "ord-002",
    orderNumber: "ORD-2026-0046",
    stage: "pushed_to_mrp",
    source: "ecommerce",
    createdAt: "2026-03-01T14:30:00Z",
    emailSubject: "February Replenishment Order",
    customer: {
      id: "cust-002",
      name: "Sarah Chen",
      email: "sarah.chen@meridianparts.com",
      phone: "(555) 876-5432",
      company: "Meridian Parts Co.",
      billingAddress: "340 Industrial Pkwy, Denver, CO 80201",
      shippingAddress: "340 Industrial Pkwy, Dock B, Denver, CO 80201",
    },
    attachments: [
      {
        id: "att-002",
        fileName: "feb-order-list.pdf",
        mimeType: "application/pdf",
        size: 890_000,
        url: "/sample-order.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-010",
        lineNumber: 1,
        rawText: "200x Steel Bolt M8 SB-M8-200",
        parsedSku: "SB-M8-200",
        parsedProductName: "Steel Bolt M8 200-Pack",
        parsedQuantity: 200,
        parsedUom: "packs",
        parsedUnitPrice: 14.5,
        matchStatus: "confirmed",
        confidence: 99,
        matchedCatalogItems: [
          {
            catalogSku: "SB-M8-200",
            catalogName: "Steel Bolt M8 200-Pack",
            catalogDescription: "Grade 8 steel bolts, M8 thread, 200 per box.",
            catalogPrice: 14.5,
            catalogUom: "pack",
          },
        ],
        issues: [],
      },
      {
        id: "li-011",
        lineNumber: 2,
        rawText: "75 Nylon Washers NW-100",
        parsedSku: "NW-100",
        parsedProductName: "Nylon Washer 100-Pack",
        parsedQuantity: 75,
        parsedUom: "packs",
        parsedUnitPrice: 6.25,
        matchStatus: "confirmed",
        confidence: 96,
        matchedCatalogItems: [
          {
            catalogSku: "NW-100",
            catalogName: "Nylon Washer 100-Count",
            catalogDescription: "Standard nylon washers, 100 per bag.",
            catalogPrice: 6.25,
            catalogUom: "bag",
          },
        ],
        issues: [],
      },
      {
        id: "li-012",
        lineNumber: 3,
        rawText: "50 Lock Washers LW-M8",
        parsedSku: "LW-M8",
        parsedProductName: "Lock Washer M8 50-Pack",
        parsedQuantity: 50,
        parsedUom: "packs",
        parsedUnitPrice: 3.75,
        matchStatus: "confirmed",
        confidence: 96,
        matchedCatalogItems: [
          {
            catalogSku: "LW-M8",
            catalogName: "Lock Washer M8 50-Pack",
            catalogDescription: "Split lock washers, M8 size. 50 per pack.",
            catalogPrice: 3.75,
            catalogUom: "pack",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 3,
    poNumber: "PO-2026-0318",
    dueDate: "28 Feb 2026",
    shipTo: "340 Industrial Pkwy, Dock B, Denver, CO 80201",
    shipVia: "UPS Ground",
    paymentTerms: "Net 15",
    parseConfidence: 97,
    parseFieldConfidence: {
      partNumber: 96,
      price: 96,
      qty: 98,
      dueDate: 94,
      shipTo: 96,
      shipVia: 92,
      paymentTerms: 94,
    },
    parseMissingFields: [],
    mrpRoutedAt: "2026-03-01T14:32:00Z",
    ingestionSourceLabel: "storefront:upload",
    demoFlow: {
      scenario: "po_match",
      stage: "po_validated",
      quoteNumber: "Q-2026-0035",
      poNumber: "PO-2026-0318",
      quoteComparison: {
        overallMatch: true,
        checks: [
          { field: "price", matches: true, quoteValue: "All lines matched", incomingValue: "All lines matched" },
          { field: "quantity", matches: true, quoteValue: "All quantities matched", incomingValue: "All quantities matched" },
          { field: "dueDate", matches: true, quoteValue: "Due dates aligned", incomingValue: "Due dates aligned" },
          { field: "drawingRev", matches: true, quoteValue: "Revisions matched", incomingValue: "Revisions matched" },
        ],
      },
      quoteSummary: {
        quoteNumber: "Q-2026-0035",
        items: [
          { sku: "SB-M8-200", name: "Steel Bolt M8 200-Pack", qty: 200, unitPrice: 14.5 },
          { sku: "NW-100", name: "Nylon Washer 100-Count", qty: 75, unitPrice: 6.25 },
          { sku: "LW-M8", name: "Lock Washer M8 50-Pack", qty: 50, unitPrice: 3.75 },
        ],
        subtotal: 3556.25,
        sentAt: "2026-02-28T10:00:00Z",
        sentTo: "sarah.chen@meridianparts.com",
      },
      poConfirmation: {
        poNumber: "PO-2026-0318",
        receivedAt: "2026-03-01T14:00:00Z",
        matchesQuote: true,
      },
      mrpPush: {
        pushedAt: "2026-03-01T14:32:00Z",
        erpOrderId: "ERP-2026-0318",
      },
      erpSync: {
        state: "acknowledged",
        timeline: [
          { label: "PO parsed from storefront upload", state: "queued", at: "2026-03-01T14:30:12Z" },
          { label: "PO matched against quote Q-2026-0035", state: "sent", at: "2026-03-01T14:31:04Z" },
          { label: "ERP order acknowledged", state: "acknowledged", at: "2026-03-01T14:32:00Z" },
        ],
      },
    },
  },
  {
    id: "ord-003",
    orderNumber: "ORD-2026-0045",
    stage: "shipped",
    source: "email",
    createdAt: "2026-02-25T11:00:00Z",
    emailSubject: "Re: Quarterly Supply Request",
    customer: {
      id: "cust-003",
      name: "Marcus Rivera",
      email: "m.rivera@toplinehardware.com",
      phone: "(555) 321-0987",
      company: "Topline Hardware LLC",
      billingAddress: "78 Main Street, Portland, OR 97201",
      shippingAddress: "900 Distribution Way, Portland, OR 97220",
    },
    attachments: [
      {
        id: "att-003",
        fileName: "supply-request-q1.png",
        mimeType: "image/png",
        size: 1_750_000,
        url: "/sample-handwritten-order.png",
      },
    ],
    lineItems: [
      {
        id: "li-020",
        lineNumber: 1,
        rawText: "500 Brass Hinges BH-SM-500",
        parsedSku: "BH-SM-500",
        parsedProductName: "Brass Hinge Small 500-Pack",
        parsedQuantity: 500,
        parsedUom: "units",
        parsedUnitPrice: 0.85,
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "BH-SM-500",
            catalogName: "Brass Hinge Small - Bulk 500",
            catalogDescription: "Small brass hinges for cabinet doors, bulk pack.",
            catalogPrice: 0.85,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-021",
        lineNumber: 2,
        rawText: '25 Drawer Slides 18" DS-18-PR',
        parsedSku: "DS-18-PR",
        parsedProductName: 'Drawer Slide 18" Pair',
        parsedQuantity: 25,
        parsedUom: "pairs",
        parsedUnitPrice: 11.0,
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "DS-18-PR",
            catalogName: 'Drawer Slide 18" Pair',
            catalogDescription: '18-inch full extension drawer slides, sold in pairs.',
            catalogPrice: 11.0,
            catalogUom: "pair",
          },
        ],
        issues: [],
      },
      {
        id: "li-022",
        lineNumber: 3,
        rawText: "40 cabinet knobs CK-RND",
        parsedSku: "CK-RND",
        parsedProductName: "Cabinet Knob Round",
        parsedQuantity: 40,
        parsedUom: "each",
        parsedUnitPrice: 3.25,
        matchStatus: "confirmed",
        confidence: 94,
        matchedCatalogItems: [
          {
            catalogSku: "CK-RND",
            catalogName: "Cabinet Knob Round - Brushed Nickel",
            catalogDescription: "Round cabinet knob, brushed nickel finish.",
            catalogPrice: 3.25,
            catalogUom: "each",
          },
        ],
        issues: [],
      },
      {
        id: "li-023",
        lineNumber: 4,
        rawText: "60 Soft-Close Hinges SC-35 35mm",
        parsedSku: "SC-35",
        parsedProductName: "Soft-Close Hinge 35mm Cup",
        parsedQuantity: 60,
        parsedUom: "each",
        parsedUnitPrice: 4.75,
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "SC-35",
            catalogName: "Soft-Close Hinge 35mm Cup",
            catalogDescription: "35mm cup soft-close cabinet hinge, 110° opening.",
            catalogPrice: 4.75,
            catalogUom: "each",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 4,
    poNumber: "PO-2026-0299",
    dueDate: "12 Mar 2026",
    shipTo: "900 Distribution Way, Portland, OR 97220",
    shipVia: "FedEx Economy",
    paymentTerms: "Net 30",
    parseConfidence: 96,
    parseMissingFields: [],
    mrpRoutedAt: "2026-02-25T11:01:00Z",
    ingestionSourceLabel: "email:attachment",
    shipmentSummary: {
      shipmentId: "shp-mock-003",
      status: "in_transit",
      carrier: "fedex",
      trackingNumber: "794644790132",
      estimatedDelivery: "2026-03-14",
      latestEventAt: "2026-03-11T08:20:00Z",
    },
    demoFlow: {
      scenario: "po_match",
      stage: "po_validated",
      quoteNumber: "Q-2026-0038",
      poNumber: "PO-2026-0299",
      quoteComparison: {
        overallMatch: true,
        checks: [
          { field: "price", matches: true, quoteValue: "All lines matched", incomingValue: "All lines matched" },
          { field: "quantity", matches: true, quoteValue: "All quantities matched", incomingValue: "All quantities matched" },
          { field: "dueDate", matches: true, quoteValue: "Due dates aligned", incomingValue: "Due dates aligned" },
          { field: "drawingRev", matches: true, quoteValue: "Revisions matched", incomingValue: "Revisions matched" },
        ],
      },
      quoteSummary: {
        quoteNumber: "Q-2026-0038",
        items: [
          { sku: "BH-SM-500", name: "Brass Hinge Small 500-Pack", qty: 500, unitPrice: 0.85 },
          { sku: "DS-18-PR", name: "Drawer Slide 18\" Pair", qty: 25, unitPrice: 11.0 },
          { sku: "CK-RND", name: "Cabinet Knob Round", qty: 40, unitPrice: 3.25 },
          { sku: "SC-35", name: "Soft-Close Hinge 35mm", qty: 60, unitPrice: 4.75 },
        ],
        subtotal: 1090.0,
        sentAt: "2026-02-22T10:00:00Z",
        sentTo: "m.rivera@toplinehardware.com",
      },
      poConfirmation: {
        poNumber: "PO-2026-0299",
        receivedAt: "2026-02-24T14:30:00Z",
        matchesQuote: true,
      },
      mrpPush: {
        pushedAt: "2026-02-25T11:01:00Z",
        erpOrderId: "ERP-2026-0299",
      },
    },
  },
  {
    id: "ord-004",
    orderNumber: "ORD-2026-0044",
    stage: "delivered",
    source: "phone",
    createdAt: "2026-02-18T08:45:00Z",
    emailSubject: "Monthly Auto-Parts Order",
    customer: {
      id: "cust-004",
      name: "Lisa Park",
      email: "lpark@velocityauto.com",
      phone: "(555) 654-3210",
      company: "Velocity Auto Supply",
      billingAddress: "2100 Motor Ave, Detroit, MI 48201",
      shippingAddress: "2100 Motor Ave, Bay 5, Detroit, MI 48201",
    },
    attachments: [
      {
        id: "att-004",
        fileName: "auto-parts-feb.pdf",
        mimeType: "application/pdf",
        size: 540_000,
        url: "/sample-order.pdf",
      },
    ],
    lineItems: [
      {
        id: "li-030",
        lineNumber: 1,
        rawText: "150 Oil Filters OF-STD-10",
        parsedSku: "OF-STD-10",
        parsedProductName: "Oil Filter Standard 10-Pack",
        parsedQuantity: 150,
        parsedUom: "packs",
        parsedUnitPrice: 32.0,
        matchStatus: "confirmed",
        confidence: 99,
        matchedCatalogItems: [
          {
            catalogSku: "OF-STD-10",
            catalogName: "Oil Filter Standard 10-Pack",
            catalogDescription: "Standard oil filter, fits most sedans. 10 per box.",
            catalogPrice: 32.0,
            catalogUom: "pack",
          },
        ],
        issues: [],
      },
      {
        id: "li-031",
        lineNumber: 2,
        rawText: "80 Brake Pads BP-CRM-4",
        parsedSku: "BP-CRM-4",
        parsedProductName: "Brake Pad Ceramic 4-Pack",
        parsedQuantity: 80,
        parsedUom: "sets",
        parsedUnitPrice: 28.5,
        matchStatus: "confirmed",
        confidence: 97,
        matchedCatalogItems: [
          {
            catalogSku: "BP-CRM-4",
            catalogName: "Brake Pad Ceramic 4-Pack",
            catalogDescription: "Ceramic brake pads, low dust. Set of 4.",
            catalogPrice: 28.5,
            catalogUom: "set",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 2,
    poNumber: "PO-2026-0253",
    dueDate: "01 Mar 2026",
    shipTo: "2100 Motor Ave, Bay 5, Detroit, MI 48201",
    shipVia: "DHL Express",
    paymentTerms: "Net 30",
    parseConfidence: 98,
    parseMissingFields: [],
    mrpRoutedAt: "2026-02-18T08:46:00Z",
    ingestionSourceLabel: "calls:simulated",
    shipmentSummary: {
      shipmentId: "shp-mock-004",
      status: "delivered",
      carrier: "dhl",
      trackingNumber: "1234567890",
      estimatedDelivery: "2026-03-01",
      latestEventAt: "2026-03-01T14:22:00Z",
    },
    demoFlow: {
      scenario: "po_match",
      stage: "po_validated",
      quoteNumber: "Q-2026-0029",
      poNumber: "PO-2026-0253",
      quoteComparison: {
        overallMatch: true,
        checks: [
          { field: "price", matches: true, quoteValue: "All lines matched", incomingValue: "All lines matched" },
          { field: "quantity", matches: true, quoteValue: "All quantities matched", incomingValue: "All quantities matched" },
          { field: "dueDate", matches: true, quoteValue: "Due dates aligned", incomingValue: "Due dates aligned" },
          { field: "drawingRev", matches: true, quoteValue: "Revisions matched", incomingValue: "Revisions matched" },
        ],
      },
      quoteSummary: {
        quoteNumber: "Q-2026-0029",
        items: [
          { sku: "OF-STD-10", name: "Oil Filter Standard 10-Pack", qty: 150, unitPrice: 32.0 },
          { sku: "BP-CRM-4", name: "Brake Pad Ceramic 4-Pack", qty: 80, unitPrice: 28.5 },
        ],
        subtotal: 7080.0,
        sentAt: "2026-02-15T14:00:00Z",
        sentTo: "lpark@velocityauto.com",
      },
      poConfirmation: {
        poNumber: "PO-2026-0253",
        receivedAt: "2026-02-17T10:30:00Z",
        matchesQuote: true,
      },
      mrpPush: {
        pushedAt: "2026-02-18T08:46:00Z",
        erpOrderId: "ERP-2026-0253",
      },
    },
  },
  {
    id: "ord-005",
    orderNumber: "ORD-2026-0043",
    stage: "pushed_to_mrp",
    source: "ecommerce",
    createdAt: "2026-02-10T16:20:00Z",
    emailSubject: "Fwd: Plumbing supplies needed",
    customer: {
      id: "cust-005",
      name: "David Okonkwo",
      email: "david@plumbprosupply.com",
      phone: "(555) 789-0123",
      company: "PlumbPro Supply",
      billingAddress: "550 Pipeline Rd, Houston, TX 77001",
      shippingAddress: "550 Pipeline Rd, Warehouse C, Houston, TX 77001",
    },
    attachments: [
      {
        id: "att-005",
        fileName: "plumbing-list.png",
        mimeType: "image/png",
        size: 1_200_000,
        url: "/sample-handwritten-order.png",
      },
    ],
    lineItems: [
      {
        id: "li-040",
        lineNumber: 1,
        rawText: "300 PVC Elbows 90deg PE-90-300",
        parsedSku: "PE-90-300",
        parsedProductName: "PVC Elbow 90-Degree Bulk 300",
        parsedQuantity: 300,
        parsedUom: "units",
        parsedUnitPrice: 0.45,
        matchStatus: "confirmed",
        confidence: 98,
        matchedCatalogItems: [
          {
            catalogSku: "PE-90-300",
            catalogName: "PVC Elbow 90° - 300 Pack",
            catalogDescription: '3/4" PVC 90-degree elbow fittings, 300 per case.',
            catalogPrice: 0.45,
            catalogUom: "unit",
          },
        ],
        issues: [],
      },
      {
        id: "li-041",
        lineNumber: 2,
        rawText: "50 copper tees 1/2",
        parsedSku: null,
        parsedProductName: 'Copper Tee 1/2"',
        parsedQuantity: 50,
        parsedUom: "each",
        parsedUnitPrice: null,
        matchStatus: "confirmed",
        confidence: 91,
        matchedCatalogItems: [
          {
            catalogSku: "CT-HALF",
            catalogName: 'Copper Tee 1/2" Fitting',
            catalogDescription: '1/2-inch copper tee fitting for residential plumbing.',
            catalogPrice: 2.1,
            catalogUom: "each",
          },
        ],
        issues: [],
      },
      {
        id: "li-042",
        lineNumber: 3,
        rawText: '20 Ball Valves BV-075 3/4"',
        parsedSku: "BV-075",
        parsedProductName: 'Ball Valve 3/4" Brass',
        parsedQuantity: 20,
        parsedUom: "each",
        parsedUnitPrice: 14.5,
        matchStatus: "confirmed",
        confidence: 95,
        matchedCatalogItems: [
          {
            catalogSku: "BV-075",
            catalogName: 'Ball Valve 3/4" Brass',
            catalogDescription: '3/4-inch brass ball valve, full port. Residential grade.',
            catalogPrice: 14.5,
            catalogUom: "each",
          },
        ],
        issues: [],
      },
    ],
    totalItems: 3,
    poNumber: "PO-2026-0208",
    dueDate: "22 Feb 2026",
    shipTo: "550 Pipeline Rd, Warehouse C, Houston, TX 77001",
    shipVia: "ShipStation",
    paymentTerms: "Net 45",
    parseConfidence: 96,
    parseFieldConfidence: {
      partNumber: 96,
      price: 95,
      qty: 98,
      dueDate: 94,
      shipTo: 96,
      shipVia: 92,
      paymentTerms: 94,
    },
    parseMissingFields: [],
    mrpRoutedAt: "2026-02-10T16:22:00Z",
    ingestionSourceLabel: "storefront:type",
    demoFlow: {
      scenario: "po_match",
      stage: "po_validated",
      quoteNumber: "Q-2026-0028",
      poNumber: "PO-2026-0208",
      quoteComparison: {
        overallMatch: true,
        checks: [
          { field: "price", matches: true, quoteValue: "All lines matched", incomingValue: "All lines matched" },
          { field: "quantity", matches: true, quoteValue: "All quantities matched", incomingValue: "All quantities matched" },
          { field: "dueDate", matches: true, quoteValue: "Due dates aligned", incomingValue: "Due dates aligned" },
          { field: "drawingRev", matches: true, quoteValue: "Revisions matched", incomingValue: "Revisions matched" },
        ],
      },
      quoteSummary: {
        quoteNumber: "Q-2026-0028",
        items: [
          { sku: "PE-90-300", name: "PVC Elbow 90-Degree Bulk 300", qty: 300, unitPrice: 0.45 },
          { sku: "CT-HALF", name: "Copper Tee 1/2\" Fitting", qty: 50, unitPrice: 2.1 },
          { sku: "BV-075", name: "Ball Valve 3/4\" Brass", qty: 20, unitPrice: 14.5 },
        ],
        subtotal: 530.0,
        sentAt: "2026-02-08T14:00:00Z",
        sentTo: "david@plumbprosupply.com",
      },
      poConfirmation: {
        poNumber: "PO-2026-0208",
        receivedAt: "2026-02-10T15:30:00Z",
        matchesQuote: true,
      },
      mrpPush: {
        pushedAt: "2026-02-10T16:22:00Z",
        erpOrderId: "ERP-2026-0208",
      },
      erpSync: {
        state: "acknowledged",
        timeline: [
          { label: "PO parsed from storefront entry", state: "queued", at: "2026-02-10T16:20:12Z" },
          { label: "PO matched against quote Q-2026-0028", state: "sent", at: "2026-02-10T16:21:15Z" },
          { label: "ERP order acknowledged", state: "acknowledged", at: "2026-02-10T16:22:00Z" },
        ],
      },
    },
  },
];
